New-PSUScript -Name "Parameters.ps1" -Description "Parameters.ps1" -Path "Parameters.ps1" 
New-PSUScript -Name "PowerShellHost.ps1" -Description "PowerShellHost.ps1" -Path "PowerShellHost.ps1" 
New-PSUScript -Name "PSVersionTable.ps1" -Description "PSVersionTable.ps1" -Path "PSVersionTable.ps1" 
New-PSUScript -Name "Pipeline.ps1" -Description "Pipeline.ps1" -Path "Pipeline.ps1" 
New-PSUScript -Name "Parent.ps1" -Description "Parent.ps1" -Path "Parent.ps1" 
New-PSUScript -Name "Child.ps1" -Description "Child.ps1" -Path "Child.ps1" 
New-PSUScript -Name "Cache.ps1" -Description "Cache.ps1" -Path "Cache.ps1" 
New-PSUScript -Name "FailedNotification.ps1" -Description "FailedNotification.ps1" -Path "FailedNotification.ps1" 
New-PSUScript -Name "FailScript.ps1" -Description "FailScript.ps1" -Path "FailScript.ps1" 
New-PSUScript -Name "Portal Script.ps1" -Description "Portal Script.ps1" -Path "Portal Script.ps1" -Role @('Administrator') -PortalOutputType "Table"